# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ea4317dcc6d09f154ba1759db238db26253d9eb643b4ae6e363f9bd23268e06acfe0f1a30599e07f08caea7ea89e6725f68f920b64bc7b967710da8c75d4db4

test:
  secret_key_base: d6d052252d212657537a8cde7709aa023a8bb20cccb02444dab313c1eaaae9b60ff8bf5fb6e7b3885ae185aca17e0a423a760e691e1e1213a9aaaf1f2f631398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
